name: publish

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v5
              with:
                  node-version: 22

            - name: Publish
              run: |
                  npm install
                  npx @vscode/vsce publish --pat ${{ secrets.VSCE_TOKEN }}
                  npx ovsx publish -p ${{ secrets.OVSX_TOKEN }}

    push-website:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Checkout Auto.dn-website repo
              uses: actions/checkout@v4
              with:
                  repository: AuTsing/Auto.dn-website
                  path: ./tmp/website
                  token: ${{ secrets.AUTODN_WEBSITE_TOKEN }}

            - name: Update
              run: |
                  cp ./CHANGELOG.md ./tmp/website/docs/changelog/extension.md

            - name: Read version
              id: read_version
              run: |
                  echo "version=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_OUTPUT

            - name: Commit
              run: |
                  cd ./tmp/website
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "update Extension to ${{ steps.read_version.outputs.version }}"
                  git push
